name: deploy-docs

on: 
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Seteup NodeJs
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn install --frozen-lockfile

    - run: yarn build
      env:
        TURBO_TOKEN: 4gC3H8jihEcGNThf9gWmfn2h
        TURBO_TEAM: caioqueiroz

    - name: Deploy storybook
      working-directory: ./packages/docs
      run: touch storybook-static/.nojekyll && yarn deploy-storybook -- --ci --existing-output-dir=storybook-static
      env:
        GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
